### PR TITLE
Add needles for awesome test

### PR DESCRIPTION
**Pull request by asdil12**
Related to issue: https://progress.opensuse.org/issues/9522

Obsoletes  #53 

Required by os-autoinst/os-autoinst-distri-opensuse#940

### CODE REVIEW

**Comment by coolo** [comment]
No need to obsolete PRs, they follow your branch

**Comment by coolo** [comment]
what's missing now is unregistering the needles these needles for minimalx. Actually it would be an idea to leave minimalx needles for DESKTOP=awesome.

**Comment by coolo** [comment]
this way you avoid needling everything twice

**Comment by okurz** [comment]
PR #53 was mine so I think @asdil12 has to create a new one unless we use a common feature branch on the main repo itself which we overwrite.
Regarding the unregistering there might be a problem with the DESKTOP variable being reused ?!?

**Comment by coolo** [comment]
I didn't say it's easy - but it's worthwhile

**Comment by asdil12** [comment]
Reusing minimalx needles for
- inst_overview
- displaymanager

**Pull request merged**
