### PR TITLE
Add kontact fatal error for workaround: bsc#1105207

### PR DESCRIPTION
**Pull request by Zaoliang**
Add workaround for kontact fatal error: bsc#1105207

we have issue with fatal error reported in bsc#1105207
add now workaround for this issue:
https://openqa.opensuse.org/tests/812844#step/kontact/14
see https://progress.opensuse.org/issues/35589
verification runs(all successful):
http://f40.suse.de/tests/89#step/kontact/
needle PR:
os-autoinst/os-autoinst-needles-opensuse#485

### CODE REVIEW

**Comment by okurz** [comment]
Should be boo#1105207 instead of bsc#110520

**Comment by okurz** [comment]
I don't see the updated commit in https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/485/commits and also no updated PR description

**Comment by okurz** [comment]
see my comment above

**Comment by Zaoliang** [comment]
again, this is strange. I can see the updates in

https://github.com/Zaoliang/os-autoinst-distri-opensuse/commit/29fb5ec62e27763e69914f1590374497cb558bc5

**Comment by okurz** [comment]
@Zaoliang the PR description is not automatically updated with the commit message

**Comment by okurz** [comment]
Ok, I updated the subject line now myself

**Pull request merged**
