### PR TITLE
Cleanup installation overview needles

### PR DESCRIPTION
**Pull request by rwx788**
We have created new needles to verify release notes button on
installation settings overview screen. It also matches other newly
created needles without button. Hence as a cleanup, we remove them to
rely only on needles with release notes button area. This removes
identified duplicates, which won't be removed automatically, as both
match.

Examples of such duplicate needles:
https://openqa.opensuse.org/tests/442300#step/installation_overview/1
https://openqa.opensuse.org/tests/442307#step/installation_overview/1
https://openqa.opensuse.org/tests/442301#step/installation_overview/1
https://openqa.opensuse.org/tests/442305#step/installation_overview/1
https://openqa.opensuse.org/tests/442253#step/installation_overview/1

### CODE REVIEW

**Comment by SergioAtSUSE** [comment]
I need a verification run ;)

**Comment by rwx788** [comment]
There are 5 runs above, do you really want me to get of them? =)

**Comment by SergioAtSUSE** [comment]
But, those are not verification runs, those are example of the duplicates, aren't they?. :confused: 

Also, I am seeing on the first example https://openqa.opensuse.org/tests/442300#step/installation_overview/1 that it is matching one needle that is deleted on this PR `inst-overview-textmode-20160831`.

A verification run would be one where there is not matching one of the deleted needles.
And also I expect the verification run to not be on openqa.opensuse.org, since this might mean that the changes are already on productive instances.

**Comment by SergioAtSUSE** [comment]
As spoken with @rwx788 
We will wait for tomorrow for that PR to also removed the next ones duplicates.

**Comment by okurz** [comment]
@rwx788 merged, now please monitor o3 jobs closely. thanks.

**Comment by rwx788** [comment]
@okurz Will do so.

**Comment by lnussel** [comment]
this breaks staging.

why does this now check for a release notes button anways? if we wanted to verify that release notes work we should have a separate test for that.

**Comment by rwx788** [comment]
@lnussel My bad, terribly sorry for that. Previously we had good_buttons test which aim was to verify release_notes button as well, but at some point needle without it was created and test became useless. For SLE we test release notes separately, but here as part of improvement we wanted to introduce new needles. Could you please point me to the staging job group you are referring to?

**Comment by lnussel** [comment]
https://openqa.opensuse.org/group_overview/2
https://openqa.opensuse.org/group_overview/6

**Comment by lnussel** [comment]
I've reverted the commit so we can continue

**Comment by nilxam** [comment]
Note that, for openSUSE, we don't have the release note button in the Staging testdvd.

**Comment by rwx788** [comment]
Was not aware of it. Then yes, let's keep it as it is after revert and if required, we add separate test for release notes. Thanks!

**Pull request merged**
