### PR TITLE
Fix problem with pressing play in vlc.pm

### PR DESCRIPTION
**Pull request by Zaoliang**
- see poo#33523 and 16516
- create a needle for match before pressing play button
- verification run:
  http://e13.suse.de/tests/2429#step/vlc

### CODE REVIEW

**Comment by kravciak** [comment]
String `/data/Big_Buck_Bunny_8_seconds_bird_clip.ogv` is not typed properly, how does needle change help?

**Comment by Zaoliang** [comment]
@kravciak the problem before pressing play is no check for correct input or too early.
So assert_screen forces it to check needle match. In this case it helps.

**Comment by Zaoliang** [comment]
@kravciak I created one needle on o3 directly and then I found that needle's position is not good because it is not same place when it tries to match. so that is why I create a new one which is work better for match. Important here is to force to check url input.

**Comment by kravciak** [comment]
Ok then, let's see if it helps

**Comment by okurz** [comment]
Looks like a good idea

**Pull request merged**
