### PR TITLE
Add package retry needle as workaround boo1018262

### PR DESCRIPTION
**Pull request by michelmno**
Used in install_and_reboot.pm

Signed-off-by: openQA web UI <openqa@abanc>

### CODE REVIEW

**Comment by coolo** [comment]
your webui signs off commits? wow :)

**Comment by michelmno** [comment]
I merged two commits  and set correctly the signoff

**Comment by michelmno** [comment]
@coolo,  is there a specific reason why this PR is not accepted while the one that used it was accepted ? https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/3070

**Comment by coolo** [comment]
I'm innocent on either

**Pull request merged**
