### PR TITLE
Workaround issue with akregator which cannot be closed

### PR DESCRIPTION
**Pull request by Zaoliang**
we have sporadic issue with closing akregator:
http://e13.suse.de/tests/10533#step/kontact/16
after killall kontact, akregator is still there
trying record_soft_failure && return if (check_screen 'akregator-not-closed')
see test runs: http://e13.suse.de/tests/10640
see ticket for more details:
https://progress.opensuse.org/issues/35589

### CODE REVIEW

**Comment by okurz** [comment]
Is there an according test adjustment PR for this already? Feels weird to have a needle for akregator which we never even wanted to start, we started akonadi and kontact

**Comment by Zaoliang** [comment]
@okurz well, I created directly 'akregator-not-closed' on 3o since this happened sporadic even after killall command.

**Comment by okurz** [comment]
typo in commit message: record_soft_failur

**Comment by Zaoliang** [comment]
@okurz corrected now, thanks!

**Comment by okurz** [comment]
please check again, the description in the PR is still outdated. Btw, this applies everytime: The PR description and the git commit message are not automatically kept in sync. I suggest you *review* your own PRs and check for mistakes like these. I forget this as well for me sometimes but it is about the fastest feedback you can get:

1. Create a PR
2. Check your own PR as if you would be another reviewer :)

**Comment by okurz** [comment]
please check the PR description again. It still states "record_soft_failur"

**Comment by okurz** [comment]
@Zaoliang the PR description is not automatically updated with the commit message

**Pull request merged**
