### PR TITLE
Remove text-login which should not be used anymore

### PR DESCRIPTION
**Pull request by Zaoliang**
see https://progress.opensuse.org/issues/34471
http://f40.suse.de/tests/5546#step/zypper_up/1 (JeOS-for-kvm-and-xen-x86_64-Build17.7-jeos@64bit_virtio-2G)
http://f40.suse.de/tests/5547#step/zypper_up/1 (Tumbleweed-NET-x86_64-Build20191126-textmode@64bit)
http://f40.suse.de/tests/5548#step/zypper_up/1 (opensuse-15.1-DVD-Updates-x86_64-Build20191127-2-textmode@64bit)
http://f40.suse.de/tests/5549#step/zypper_up/1 (opensuse-15.0-DVD-Updates-x86_64-Build20191127-2-textmode@64bit)
https://openqa.opensuse.org/tests/1096840#step/reboot_eject_cd/1 still use text-login which got 
replaced now: https://openqa.opensuse.org/tests/1097178
see PR: 
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/9014

### CODE REVIEW

**Comment by DimStar77** [comment]
https://openqa.opensuse.org/tests/1097979/file/autoinst-log.txt referenced text-login needles and now fails in reruns

https://openqa.opensuse.org/tests/1099159#next_previous

**Comment by DimStar77** [comment]
```
> os-autoinst-distri-opensuse> grep text-login . -r
./lib/sles4sap.pm:                  text-login linux-login started-x-displaymanager-info)
./lib/susedistribution.pm:            assert_screen "text-login", 10;
./lib/susedistribution.pm:        assert_screen(["text-logged-in-$user", "text-login"], 60);
./tests/console/sle15_workarounds.pm:        assert_screen(["tty2-selected", 'text-login', 'text-logged-in-root', 'generic-desktop']);
./tests/console/copy_iso_to_external_drive.pm:    assert_screen "text-login";
./tests/installation/reboot_eject_cd.pm:    assert_screen('text-login');
./tests/virt_autotest/reboot_and_wait_up.pm:        assert_screen("text-login", 600);
./tests/systemd_testsuite/test_09_issue_2691.pm:    send_key_until_needlematch('text-login', 'ret', 360, 5);
```

Maybe that gives some clue where it might break

**Comment by DimStar77** [comment]
Another fallout: https://openqa.opensuse.org/tests/1099269#step/copy_iso_to_external_drive/27

**Comment by okurz** [comment]
@SergioAtSUSE @Zaoliang careful when you remove needles. Please monitor jobs carefully after merging. I have reveted the delete for now. You now know better what to check. Also I recommend when deleting needles to check where they have been used last, e.g. on https://openqa.opensuse.org/admin/needles

**Pull request merged**
