### PR TITLE
Enable kdump via YaST2, needles

### PR DESCRIPTION
**Pull request by mnowaksuse**
Needles for https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/1462.

### CODE REVIEW

**Comment by okurz** [comment]
please track the test on o3

**Comment by mnowaksuse** [comment]
Do you have pointer for group->job where toolchain tests are being executed?

**Comment by Soulofdestiny** [comment]
@mnowaksuse 
https://openqa.suse.de/tests/445896#step/crash/9
It's failing at the moment - can you give me a hint, why?

**Comment by Soulofdestiny** [comment]
nvm - test was triggered before the needle merge

**Comment by mnowaksuse** [comment]
The SLE needles are waiting here: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/155

**Pull request merged**
