### PR TITLE
Add workaround needle for multi_users_dm-xfce

### PR DESCRIPTION
**Pull request by asdil12**
This reverts commit 23db8e1635886f205eff0e3ac625e416d32b7243.

There is no needle for the xfce login manager by intention
because the usability for the login manager is bad when
there are many users in passwd file.

See https://progress.opensuse.org/issues/9694
and https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/1102

The test is meant to fail for xfce until the login manager is fixed.
This shouldn't be a problem as it isn't marked as important.

### CODE REVIEW

**Comment by coolo** [comment]
where is your bug report about it?

**Comment by coolo** [comment]
If you have one, rename the needle to include that bug number and add a workaround property. A missing needle really doesn't document much

**Comment by asdil12** [comment]
Why would I need a bug report for that?

**Comment by asdil12** [comment]
I don't see the need of a workaround needle.
This test is not flagged as important so it won't affect the overall result.
So it can fail without affecting other tests.

**Comment by coolo** [comment]
yes, but it affects every day's review.

**Comment by coolo** [comment]
and if you don't feel the need to create a bug report - why did you feel the need to write a test that fails?

**Comment by sysrich** [comment]
Ping - are you going to file a bug about this?

**Comment by asdil12** [comment]
https://bugzilla.opensuse.org/show_bug.cgi?id=981596

**Comment by okurz** [comment]
there is a bug and a test, can you make a workaround needle according to https://progress.opensuse.org/projects/openqatests/wiki#applying-quotworkaroundquot-needles ?

**Comment by asdil12** [comment]
Converted the existing needle into a workaround needle

**Comment by sysrich** [comment]
Can you edit the PR subject to match the new purpose of this PR - just so no one gets confused after we merge it ;)

**Comment by asdil12** [comment]
done

**Pull request merged**
