### PR TITLE
yast2_bootloader-yast2-bootloader_pwd_filled_up-tw

### PR DESCRIPTION
**Pull request by kinderp**
Check if pwd is set correctly in yast2-bootloader
(Bootloader Options tab)

### CODE REVIEW

**Comment by czerw** [comment]
Why your yast2_bootloader PR contains commits related to Thunderbird?

**Comment by kinderp** [comment]
I messed up during rebase maybe, it should be ok now

**Comment by foursixnine** [comment]
@kinderp / @czerw no more changes needed?

**Comment by asdil12** [comment]
The name of the needle in this PR doesn't match the requirement for needle names to contain a timestamp.

Fix: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/588

**Pull request merged**
