### PR TITLE
Add awesome needles

### PR DESCRIPTION
**Pull request by asdil12**
needles related to awesome tests

### CODE REVIEW

**Comment by okurz** [comment]
* First line of each commit message should start with capital letter, see
  * http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
  * https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message
  * http://chris.beams.io/posts/git-commit/

* [displaymanager-awesome-20151221.png](https://github.com/asdil12/os-autoinst-needles-opensuse/blob/awesome/displaymanager-awesome-20151221.png) looks like [first_boot-displaymanager-20151221.png](https://github.com/asdil12/os-autoinst-needles-opensuse/blob/awesome/first_boot-displaymanager-20151221.png) looks like https://openqa.opensuse.org/tests/105705/modules/first_boot/steps/1 . why are the two new images necessary? Probably it is me not knowing openQA enough

* why the "generic" name for [x11_login-generic-desktop-20151221.json](https://github.com/asdil12/os-autoinst-needles-opensuse/blob/awesome/x11_login-generic-desktop-20151221.json) ?

**Comment by coolo** [comment]
x11_login-generic-desktop-20151221 deserves a workaround property btw as the bulb is clearly misrendered. And it should not be used for other desktops, i.e. it needs to be tagged as DESKTOP-awesom

**Comment by okurz** [comment]
why doesn't the background resemble https://github.com/madanyang/awesome-branding-opensuse/blob/master/themes/openSUSE/background.jpg ?

**Comment by okurz** [comment]
#53 to replace this PR:
* tag "ENV-DESKTOP-awesome" updated
* redundant needle deleted
* updated screenshot with Tumbleweed background: Does not matter for the test but does not confuse with distorted light bulb

**Pull request closed without merging**
