### PR TITLE
Support virtualization tests run with ipmi backend in textmode

### PR DESCRIPTION
**Pull request by Julie-CAO**
Vitualization tests will be deployed in O3 to test Tumbleweed snapshot. The tests installs TW in textmode with ipmi backend(baremetal machines). The required needles were created in my indevidual openqa, and more needles will be added when the tests start to run in O3.

the test script PR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15253

### CODE REVIEW

**Comment by Julie-CAO** [comment]
Hi, anyone who is maintainer can help with this?  It is  `First-time contributors need a maintainer to approve`

**Comment by Julie-CAO** [comment]
Hi, I am not authorized to access the maintainers in https://github.com/orgs/os-autoinst/teams/tests-maintainer. I need someone's approvel from @os-autoinst/tests-maintainer

**Comment by Martchus** [comment]
@os-autoinst/tests-maintainer Can anybody help to review this PR?

**Comment by asdil12** [comment]
Merged as the corresponding PR for the tests are already merged. Too late for me to see the typo msg ^^.

**Comment by Julie-CAO** [comment]
Thank you!

**Pull request merged**
