### PR TITLE
Re-work yast2_ftp.pm and add required needles:

### PR DESCRIPTION
**Pull request by Zaoliang**
*       yast2_ftp-ftp_directories
*	yast2_ftp-ftp_umask_value
*	yast2_ftp-ftp_welcome_mesage
*	yast2_ftp-ftp_welcome_message
*	yast2_ftp_anonymous_upload
*	yast2_ftp_authentication_enabled
*	yast2_ftp_create_upload_dir_confirm
*	yast2_ftp_directory_browse
*	yast2_ftp_expert_settings
*	yast2_ftp_general_directories
*	yast2_ftp_performance-settings
*	yast2_ftp_start-up_selected
*	yast2_tftp_authentication_selected
*	yast2_tftp_general_selected
*	yast2_tftp_performance_selected
*      remove yast2_ftp-ftp_expert_settings
*      remove yast2_ftp-ftp_expert_settings_done

### CODE REVIEW

**Comment by okurz** [comment]
Subject line should not include ':'

Don't repeat filenames in commit message.

Please state why you add these needles, e.g. 'Fix test failure on Tumbleweed'

**Comment by Zaoliang** [comment]
okurz: commit message got changed now.

**Comment by okurz** [comment]
needs corresponding test change

**Comment by Zaoliang** [comment]
okurz: pull request for yast2_ftp.pm is done now.

**Comment by okurz** [comment]
+1

**Pull request closed without merging**
