### PR TITLE
Add flatpak needles

### PR DESCRIPTION
**Pull request by grisu48**
Needles for flatpak test on Tumbleweed

### CODE REVIEW

**Comment by perlpunk** [comment]
Typo in title/commit (flapak -> flatpak) :)

**Comment by grisu48** [comment]
> Typo in title/commit (flapak -> flatpak) :)

That happens a lot to me :sweat_smile: Thanks for looking!

**Comment by DimStar77** [comment]
> > Typo in title/commit (flapak -> flatpak) :)
> 
> That happens a lot to me 😅 Thanks for looking!

So, drugs you corrected the future of the PR, but not actually the color message in the git tree?

(Coming here as flatpak test was merged, but obviously has now missing needles, making TW tests fail)

**Comment by grisu48** [comment]
> > > Typo in title/commit (flapak -> flatpak) :)
> > 
> > 
> > That happens a lot to me sweat_smile Thanks for looking!
> 
> So, drugs you corrected the future of the PR, but not actually the color message in the git tree?
> 
> (Coming here as flatpak test was merged, but obviously has now missing needles, making TW tests fail)

Sorry, they got forgotten (I really do mostly console stuff). [poo#88585](https://progress.opensuse.org/issues/88585) addresses this issue and including the needles fixes the [verification run](http://duck-norris.qam.suse.de/tests/5094#details).

Should be good again in the next runs.

**Pull request merged**
