### PR TITLE
Bring back needles deleted by accident

### PR DESCRIPTION
**Pull request by foursixnine**
I think this would do the trick: 

git revert --no-edit   0ef47e055b2dfe65485d46508d4e7054bdfbb8cd...96ce91f469628736e99fabffcf8a4d133525bcb2

### CODE REVIEW

**Comment by foursixnine** [comment]
If anybody got the command for squashing all that in batch, my poor git knowledge would appreciate it :D

**Comment by foursixnine** [comment]
Ok, triple checked, all good... self merging

**Comment by tonyyuan1** [comment]
Hello @foursixnine is the merging complete? We just pulled the master. Some tests still failed due to needle missing. 
http://d453.qam.suse.de/tests/1308#step/boot_from_pxe/14

**Comment by foursixnine** [comment]
@tonyyuan1 do you have other jobs that are missing needles? https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/commits/master?search=virttest-pxe-menu

**Comment by tonyyuan1** [comment]
http://openqa.qam.suse.cz/tests/35159
This boot_from_pxe relies on a lot of needles.   We use it to install sles from 12.3 to 15.4. 
We currently reset hard to a commit of Dec 31 2021 as workaround.

**Pull request merged**
