### PR TITLE
installer_desktopselection-textmode-selected-text-20161004 for PowerPC

### PR DESCRIPTION
**Pull request by michelmno**
Signed-off-by: Michel Normand <normand@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by coolo** [comment]
This needle is wrong as it at least needs to contain some tags excluding it on non text installation.

**Comment by michelmno** [comment]
I assume the missing  tag was also valid for the two previous needles:
===
$grep -Hn -A2 tags installer_desktopselection-textmode-selected-text*json
installer_desktopselection-textmode-selected-text-20160825.json:11:  "tags": [
installer_desktopselection-textmode-selected-text-20160825.json-12-    "textmode-selected"
installer_desktopselection-textmode-selected-text-20160825.json-13-  ],
--
installer_desktopselection-textmode-selected-text-20160831.json:2:  "tags": [
installer_desktopselection-textmode-selected-text-20160831.json-3-    "textmode-selected"
installer_desktopselection-textmode-selected-text-20160831.json-4-  ],
--
installer_desktopselection-textmode-selected-text-20161004.json:12:  "tags": [
installer_desktopselection-textmode-selected-text-20161004.json-13-    "textmode-selected"
installer_desktopselection-textmode-selected-text-20161004.json-14-  ]
===

**Comment by coolo** [comment]
yes. script/modify_needle --add-tags=ENV-VIDEOMODE-text *-text*.json and review :)

**Comment by coolo** [comment]
(the \* was eaten by markdown)

**Comment by michelmno** [comment]
I only modified the three json files with same prefix name in above commit, 
There are more xxx-text.json as suggested by #coolo  I would suggest to modify them in another commit to ease tracking.

**Comment by okurz** [comment]
Could you please reference any tickets reporting on test failures or the test failures itself you want to fix? E.g. just drop the URL to a failing test case on openqa.opensuse.org

**Comment by michelmno** [comment]
@okurz   I am using an openQA instance in  IBM intranet so not able to give you an url on failing test case. But anyway analysing deeper the failure seems to be related to a a lost down key and selection of Server rather than Other checkbox in  while executing installer_desktopselection.pm
I tried to recreate the failure but with no success.
I am closing this PR as useless.
```
/var/lib/openqa/script/client jobs post ISO=openSUSE-Tumbleweed-DVD-ppc64le-Snapshot20160907-Media.iso  DISTRI=opensuse VERSION=Tumbleweed FLAVOR=DVD ARCH=ppc64le BUILD=20160907 MACHINE=ppc64le QEMU=ppc64 OFW=1 QEMUCPU=host VGA=std WORKER_CLASS=qemu_ppc64le Test=textmode HDDSIZEGB=30 TEST=textmode DESKTOP=textmode  TEXTMODE=1 NOIMAGES=1 VIDEOMODE=text
```

**Pull request closed without merging**
