### PR TITLE
Needles for storage-ng

### PR DESCRIPTION
**Pull request by ancorgs**
Now that https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/3409 is merged, these should be the needles needed to make the whole thing work with storage-ng (Staging:E right now)

### CODE REVIEW

**Comment by okurz** [comment]
Please fix the authors of the git commits to correspond to real persons

**Comment by ancorgs** [comment]
@rwx788 Can you take care?

**Comment by okurz** [comment]
It's fine, I hijacked the commits and pushed to master

**Comment by rwx788** [comment]
@okurz thanks, I was too slow =)

**Pull request closed without merging**
