### PR TITLE
new needle desktop-at-first-boot-minimalx-ppc64

### PR DESCRIPTION
**Pull request by michelmno**
required as workaround for ppc64 because background image
and icons are not correctly displayed tracked at least by bug
https://bugzilla.suse.com/show_bug.cgi?id=929462

This is a workaround needle for gpt, lvm, minimalx tests
that started to fail between 20160927 and 20161010:
https://openqa.opensuse.org/tests/297609#previous
There is no more indication of what was the previously used needle,
this is the reason why I am creating this new needle.

Signed-off-by: Michel Normand <normand@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by okurz** [comment]
thank you. we try to follow a convention for workaround needles so that we know to which bug it refers, please see https://progress.opensuse.org/projects/openqatests/wiki/#applying-quotworkaroundquot-needles

**Comment by DimStar77** [comment]
For reference, the needle that matched before was removed with commit c709defcd6f404efd05c667e5f9ad8dff7d731ba

**Comment by okurz** [comment]
I see, and it wasn't named properly. Maybe a better approach then is to just revert the deletion and update the name.

**Comment by michelmno** [comment]
arg, I forgot the bug number :(

**Comment by coolo** [comment]
and the tags and ... - I actually don't see any reason not to merge this one instead.

**Comment by michelmno** [comment]
Do I need something else for this PR on my side after change made in https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/129/commits/1d0a169e9fa626d4f9f3df91409673e0a0e61387

**Pull request merged**
