### PR TITLE
Update workaround needles for boo#1025622 to poo#19396

### PR DESCRIPTION
**Pull request by okurz**
https://bugzilla.suse.com/show_bug.cgi?id=1025622 has been closed as invalid,
https://progress.opensuse.org/issues/19396 is the follow-up.

### CODE REVIEW

**Comment by okurz** [comment]
*bump*

**Comment by SergioAtSUSE** [comment]
I need a verification run ;)

**Comment by nicksinger** [comment]
Filenames between json and png match so LGTM. But I agree with @SergioAtSUSE just for the sake of safety.

**Comment by okurz** [comment]
`;)` to me means you don't actually need a verification run so I am reading @nicksinger's LGTM

**Pull request merged**
