### PR TITLE
Add texmode testsuite for ext3,xfs and btrfs

### PR DESCRIPTION
**Pull request by jknphy**
- Related ticket: https://progress.opensuse.org/issues/30433
- Parameters to be configured for new test suites:
  `DESKTOP=textmode FILESYSTEM=ext4 FILESYSTEM=ext3 or FILESYSTEM=xfs or FILESYSTEM=btrfs VIDEOMODE=text and TEST=ext4 or TEST=ext3 or TEST=xfs or TEST=btrfs 
- Verification runs: 
  - [opensuse-Tumbleweed-DVD-x86_64-Build20180602-ext4_textmode@64bit ](http://dhcp254.suse.cz/tests/1532#step/partitioning_filesystem/10)
  - [opensuse-Tumbleweed-DVD-x86_64-Build20180602-btrfs@64bit](http://dhcp254.suse.cz/tests/1523#step/partitioning_filesystem/11)
  - [opensuse-Tumbleweed-DVD-x86_64-Build20180602-ext3@64bit](http://dhcp254.suse.cz/tests/1525#step/partitioning_filesystem/9)
  - [opensuse-Tumbleweed-DVD-x86_64-Build20180602-xfs@64bit](http://dhcp254.suse.cz/tests/1524#step/partitioning_filesystem/12)
  - [opensuse-15.0-DVD-x86_64-Build267.2-ext4_textmode@64bit](http://dhcp254.suse.cz/tests/1533#step/partitioning_filesystem/10)
  - [opensuse-Tumbleweed-DVD-ppc64le-Build20180530-ext4@ppc64le NOT YET]()

### CODE REVIEW

**Comment by SergioAtSUSE** [comment]
I think you should make it clearer in the comment that FILESYSTEM=ext3, FILESYSTEM=xfs, FILESYSTEM=btrfs. And, it should be better if we test ext4 instead of ext3.

**Comment by jknphy** [comment]
ext4 is already tested for TW.

**Comment by SergioAtSUSE** [comment]
Not on textmode installation: https://openqa.opensuse.org/tests/686325#step/welcome/1

**Comment by jknphy** [comment]
All verification provided except for ppc. My openQA version is too updated comparing with the one in the ppc worker. Could you please @SergioAtSUSE run it for me? With that I think we have reached good test coverage. I used to clone it: c[](lone_job.pl --skip-chained-deps --from https://openqa.opensuse.org 685123 FILESYSTEM=ext4 TEST=ext4 INSTALLONLY=1)

**Comment by SergioAtSUSE** [comment]
I also have problems creating a verification run.
Since this PR only contains new needles and cannot break anything, I am merging it.

Please, create a new PR with ppc64le needles.

**Pull request merged**
