### PR TITLE
Add yast-still-running for dialog shown in foreground (poo#19198)

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by coolo** [comment]
isn't this install-shell?

**Comment by okurz** [comment]
hm, good point. It *should* be but the post_fail_hook of y2logstep looks for root-console as fallback when it can't find yast-still-running in http://lord.arch/tests/6259#step/start_install/13 . Should we update yast-still-running instead?

**Comment by coolo** [comment]
most definitely. this screen should hit yast-still-running

**Comment by okurz** [comment]
@coolo updated

**Pull request merged**
