### PR TITLE
Update regression-other test cases to Tumbleweed

### PR DESCRIPTION
**Pull request by yuanren10**
We are aim to test "brasero", "gnomeapps", "totem"
"tracker" on Tumbleweed, like [osd#1883267](https://openqa.suse.de/tests/1883267)

Reference:
[POO#23906](https://progress.opensuse.org/issues/23906)

Verification Run:
[create_hdd_gnome](http://10.67.19.67/tests/464)
[qam-regression-other](http://10.67.19.67/tests/464)

### CODE REVIEW

**Comment by yuanren10** [comment]
**testsuites should add to o.o.o:**
BOOT_HDD_IMAGE=1
DESKTOP=gnome
HDD_1=%DISTRI%-%VERSION%-%ARCH%-%BUILD%-%DESKTOP%@%MACHINE%.qcow2
REGRESSION=other
START_AFTER_TEST=create_hdd_gnome

**Note:**
There are some cases different with  [osd#1883267](https://openqa.suse.de/tests/1883267), which is test on SLE. 
For example, " shotwell", " virtualization", and parts of " tracker" not test on Tumbleweed. Because these cases only run under `if (is_sle('>=12-sp2') && is_sle('<15')) ` in "lib/main_common.pm". And they didn't installed by default on Tumbleweed. 

So, I will update lib/main_common.pm and install them to do the test if necessary.

**Comment by yuanren10** [comment]
Prerequisite is [#5492](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/5492)

**Comment by yuanren10** [comment]
@rwx788 @okurz Is there any ideas about that or we can add this test suites and run.

**Comment by yuanren10** [comment]
I think we should install them to do a test completely. I will update now.

**Comment by okurz** [comment]
hi, both verification run URLs point to the same job, both create_hdd. I assume the second URL is wrong then. http://10.67.19.67/tests/493 looks promising though :)

**Comment by okurz** [comment]
needles themselves look fine though, let's merge

**Comment by rwx788** [comment]
@yuanren10 I've created test suite, but to which job group should I add it? I could not find where we have regression-gnome. On top we have some regression-installation, which creates qcow image for regression-gnome. Do you know if it's used anywhere?

**Comment by yuanren10** [comment]
@okurz , I have tested successfully. But now, I can't install "brasero". Because "create_hdd" had clear zypper repo. So, please revert firstly, and wait for me to update all test cases. By the way, I had to add oss_repo into. [not_found_package](http://10.67.19.67/tests/774#step/brasero_launch/23)

**Comment by yuanren10** [comment]
@rwx788 I don't think we have regression-gnome and regression-installation. But we have create_hdd_gnome same with regression-installation on SLE

**Comment by rwx788** [comment]
@yuanren10 test suites are there on o3, but seems that they are not a part of any job group. So should I add it to the main TW group? Regarding repos, we don't just clear them, but add them again: https://openqa.opensuse.org/tests/738867#step/zypper_ar/2 so I guess you're using old image which has repo added for old snapshot, so mirror got cleaned up.

**Comment by yuanren10** [comment]
@rwx788 Yes, this is a new job group for TW. you should

**Comment by yuanren10** [comment]
@rwx788 Yes, it belongs to main TW group.

**Comment by yuanren10** [comment]
@rwx788 regarding repo problem, yes, you are right. Very helpful. I will update verification right now. Thanks.

**Comment by rwx788** [comment]
@yuanren10 I've added test suite to the TW job group, so now we can either wait for the new build, or trigger it manually using isos post.

**Pull request merged**
